export const FETCH_INTHEATRE_MOVIE_REQUEST = 'FETCH_INTHEATRE_MOVIE_REQUEST';
export const FETCH_INTHEATRE_MOVIE_SUCCESS = 'FETCH_INTHEATRE_MOVIE_SUCCESS';
export const FETCH_INTHEATRE_MOVIE_ERROR = 'FETCH_INTHEATRE_MOVIE_ERROR';
